server:
  port: ${SERVER_PORT:8082}

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: schedule-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/schedule_db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
